// src/components/VmLauncher.vue
<template>
  <div class="launcher">
    <div class="launcher-inner">
      <div class="launcher-shell-selector">
        <p class="launcher-shell-selector-title">
          Generated shell script
        </p>
        <div
          v-for="delimeterOption in delimeterOptions"
          :key="delimeterOption.value"
          class="form-check form-check-inline"
        >
          <input
            :id="'delimeterOption' + delimeterOption.value"
            v-model="delimeter"
            class="form-check-input"
            type="radio"
            name="delimeter"
            :value="delimeterOption.value"
          >
          <label
            class="form-check-label"
            :for="'delimeterOption' + delimeterOption.value"
          >{{ delimeterOption.text }}</label>
        </div>
      </div>
      <div class="launcher-script">
        <code>{{ cmdLine }}</code>
        <button
          type="button"
          class="btn btn-outline-primary btn-sm launcher-script-btn-clipboard"
          @click="copyScriptToClipboard"
        >
          Copy
        </button>
      </div>
      <div class="launcher-panel">
        <button
          type="button"
          class="btn btn-primary"
          @click="launchVm"
        >
          Launch VM
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import { SHELL_NEW_LINE_DELIMETERS } from '../enums';

export default {
    name: 'VmLauncher',
    data() {
        return {
            delimeterOptions: SHELL_NEW_LINE_DELIMETERS,
            delimeter: SHELL_NEW_LINE_DELIMETERS[0].value,
        };
    },
    computed: {
        cmdArgs() {
            return this.$store.getters['vm/params'];
        },
        cmdLine() {
            return this.cmdArgs.join(` ${this.delimeter}\n`);
        },
    },
    methods: {
        copyScriptToClipboard() {
            navigator.clipboard.writeText(this.cmdLine);
        },
        launchVm() {
            const args = JSON.parse(JSON.stringify(this.cmdArgs));

            electron.vmManager.launchVm(args.slice(1)); // eslint-disable-line
        },
    },
};
</script>

<style>
.launcher {
  position: relative;
  height: 100%;
}

.launcher-inner {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
  gap: 1rem;
  height: 100%;
  overflow: hidden;
}

.launcher-shell-selector-title {
  margin-bottom: 0.5rem;
}

.launcher-script {
  position: relative;
  display: flex;
  overflow: hidden;
  flex-grow: 1;
}

.launcher-script code {
  white-space: pre;
  overflow: auto;
  width: 100%;
}

.launcher-script-btn-clipboard {
  position: absolute;
  top: 0.65rem;
  right: 0.65rem;
  z-index: 10;
  display: block;
  opacity: 0.5;
  padding: 0.25rem 0.5rem;
  font-size: 0.65em;
  color: #0d6efd;
  background-color: #fff;
  border: 1px solid;
  border-radius: 0.25rem;
}

.launcher-script-btn-clipboard:hover {
  opacity: 1;
}

.launcher-panel {
  display: flex;
  flex-direction: row;
  gap: 0.5rem;
}
</style>

// src/components/VmLauncher/index.tsx
import * as React from 'react';
import { useState } from 'react';

import { HTMLOption } from '../../types';
import { Shell } from '../../enums';
import { useAppSelector } from '../../store/hooks';
import { buildQemuCmdArgs, getShellMultilineDelimeter } from '../../utils';

import './index.css';

const ShellList: Array<HTMLOption<Shell>> = [
    {
        text: 'cmd',
        value: Shell.CMD,
    },
    {
        text: 'PowerShell',
        value: Shell.POWERSHELL,
    },
    {
        text: 'bash',
        value: Shell.BASH,
    },
];

export function VmLauncher() {
    const [shell, setShell] = useState(Shell.CMD);
    const config = useAppSelector(state => state.vm);
    const system = useAppSelector(state => state.system);

    const delimeter = getShellMultilineDelimeter(shell);
    const qemuArgs = buildQemuCmdArgs(config, system);
    const script = qemuArgs.join(` ${delimeter}\n`);

    const copyToClipboard = () => {
        navigator.clipboard.writeText(script);
    };

    const launchVm = () => {
        electron.vmManager.launchVm(qemuArgs.slice(1));
    };

    return (
        <div className="launcher">
            <div className="launcher-inner">
                <div className="launcher-shell-selector">
                    <p className="launcher-shell-selector-title">Generated shell script</p>
                    {ShellList.map(({ text, value }) => (
                        <div className="form-check form-check-inline" key={value}>
                            <input
                                id={`delimeter${value}`}
                                className="form-check-input"
                                type="radio"
                                name="delimeter"
                                value={value}
                                onChange={({ target }) => setShell(target.value as Shell)}
                                checked={shell == value}
                            />
                            <label htmlFor={`delimeter${value}`} className="form-check-label">
                                {text}
                            </label>
                        </div>
                    ))}
                </div>
                <div className="launcher-script">
                    <code>{script}</code>
                    <button
                        type="button"
                        className="btn btn-outline-primary btn-sm launcher-script-btn-clipboard"
                        onClick={copyToClipboard}
                    >
                        Copy
                    </button>
                </div>
                <div className="launcher-panel">
                    <button type="button" className="btn btn-primary" onClick={launchVm}>
                        Launch VM
                    </button>
                </div>
            </div>
        </div>
    );
}
