// src/components/AudioDevice.tsx
import * as React from 'react';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { setAudioEnabled } from '../store/slices/vm';

export function AudioDevice() {
    const { enabled } = useAppSelector(state => state.vm.audio);
    const dispatch = useAppDispatch();

    return (
        <div>
            <div className="form-check">
                <input
                    id="audioEnabled"
                    className="form-check-input"
                    type="checkbox"
                    checked={enabled}
                    onChange={event => dispatch(setAudioEnabled(event.target.checked))}
                />
                <label className="form-check-label" htmlFor="audioEnabled">
                    Enable audio device
                </label>
            </div>
        </div>
    );
}

// src/components/vm/AudioDevice.vue
<template>
  <div>
    <div class="form-check">
      <input
        id="audioEnabled"
        v-model="audioEnabled"
        class="form-check-input"
        type="checkbox"
      >
      <label
        class="form-check-label"
        for="audioEnabled"
      >
        Enable audio device
      </label>
    </div>
  </div>
</template>

<script>
export default {
    name: 'AudioDevice',
    computed: {
        audioEnabled: {
            get() {
                return this.$store.state.vm.config.audio.enabled;
            },
            set(value) {
                this.$store.commit('vm/patchConfig', {
                    audio: {
                        enabled: value,
                    },
                });
            },
        },
    },
};
</script>
