// src/components/BootDevice.tsx
import * as React from 'react';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { setBootDevice } from '../store/slices/vm';
import { BootDevice as BootDeviceEnum } from '../enums';

const BootDeviceList: Array<{ text: string; value: BootDeviceEnum }> = [
    {
        text: 'CD-ROM',
        value: BootDeviceEnum.CD_ROM,
    },
    {
        text: 'Hard drive',
        value: BootDeviceEnum.HARD_DRIVE,
    },
    {
        text: 'Network',
        value: BootDeviceEnum.NETWORK,
    },
];

export function BootDevice() {
    const bootDevice = useAppSelector(state => state.vm.bootDevice);
    const dispatch = useAppDispatch();

    return (
        <div>
            <label htmlFor="bootDevice" className="form-label">
                Boot device
            </label>
            <select
                id="bootDevice"
                className="form-select"
                value={bootDevice}
                onChange={event => dispatch(setBootDevice(event.target.value as BootDeviceEnum))}
            >
                {BootDeviceList.map(({ text, value }) => (
                    <option key={value} value={value}>
                        {text}
                    </option>
                ))}
            </select>
        </div>
    );
}

// src/components/vm/BootDevice.vue
<template>
  <div>
    <label
      for="bootDevice"
      class="form-label"
    >Boot device</label>
    <select
      id="bootDevice"
      v-model="bootDevice"
      class="form-select"
    >
      <option
        v-for="option in bootDeviceOptions"
        :key="option.value"
        :value="option.value"
      >
        {{ option.text }}
      </option>
    </select>
  </div>
</template>

<script>
import { BOOT_OPTIONS } from '@/enums';

export default {
    name: 'BootDevice',
    data() {
        return {
            bootDeviceOptions: BOOT_OPTIONS,
        };
    },
    computed: {
        bootDevice: {
            get() {
                return this.$store.state.vm.config.bootDevice;
            },
            set(value) {
                this.$store.commit('vm/config/patch', {
                    bootDevice: value,
                });
            },
        },
    },
};
</script>
