// src/components/HardDrive.tsx
import * as React from 'react';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { setHardDriveEnabled, setHardDrivePath } from '../store/slices/vm';

export function HardDrive() {
    const { enabled, path } = useAppSelector(state => state.vm.drive);
    const dispatch = useAppDispatch();

    const onChangeEnabledHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
        const value = event.target.checked;

        dispatch(setHardDriveEnabled(value));
    };

    const onClickSelectHandler = () => {
        dispatch(setHardDrivePath());
    };

    return (
        <div>
            <label htmlFor="drivePath" className="form-label">
                Hard drive
            </label>
            <div className="input-group mb-2">
                <input id="drivePath" className="form-control" type="text" value={path} disabled={!enabled} readOnly />
                <button
                    className="btn btn-outline-primary"
                    type="button"
                    onClick={onClickSelectHandler}
                    disabled={!enabled}
                >
                    Select
                </button>
            </div>
            <div>
                <div className="form-check">
                    <input
                        id="driveEnabled"
                        className="form-check-input"
                        type="checkbox"
                        checked={enabled}
                        onChange={onChangeEnabledHandler}
                    />
                    <label className="form-check-label" htmlFor="driveEnabled">
                        Enabled
                    </label>
                </div>
            </div>
        </div>
    );
}

// src/components/vm/HardDrive.vue
<template>
  <div>
    <label
      for="drivePath"
      class="form-label"
    >Hard drive
    </label>
    <div class="input-group mb-2">
      <input
        id="drivePath"
        class="form-control"
        type="text"
        :value="drivePath"
        :disabled="!driveEnabled"
        readonly
      >
      <button
        class="btn btn-outline-primary"
        type="button"
        :disabled="!driveEnabled"
        @click="requestDrivePath"
      >
        Select
      </button>
    </div>
    <div>
      <div class="form-check">
        <input
          id="driveEnabled"
          v-model="driveEnabled"
          class="form-check-input"
          type="checkbox"
        >
        <label
          class="form-check-label"
          for="driveEnabled"
        >
          Enabled
        </label>
      </div>
    </div>
  </div>
</template>

<script>
export default {
    name: 'HardDrive',
    computed: {
        driveEnabled: {
            get() {
                return this.$store.state.vm.config.drive.enabled;
            },
            set(value) {
                this.$store.commit('vm/config/drive/setEnabled', value);
            }
        },
        drivePath() {
            return this.$store.state.vm.config.drive.path;
        }
    },
    methods: {
        async requestDrivePath() {
            // eslint-disable-next-line no-undef
            const path = await electron.vmConfig.requestDrivePath();

            this.$store.commit('vm/config/drive/setPath', path.replaceAll('\\', '\\\\'));
        },
    }
};
</script>
