// src/components/Ram.tsx
import * as React from 'react';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { setMemory } from '../store/slices/vm';

export function Ram() {
    const system = useAppSelector(state => state.system);
    const memory = useAppSelector(state => state.vm.memory);
    const dispatch = useAppDispatch();

    return (
        <div>
            <label htmlFor="memory" className="form-label">
                RAM
            </label>
            <div className="input-group">
                <input
                    id="memory"
                    type="number"
                    className="form-control"
                    value={memory}
                    onChange={event => dispatch(setMemory(Number.parseInt(event.target.value)))}
                    min="1"
                    max={system.memory}
                />
                <span className="input-group-text">GiB</span>
            </div>
        </div>
    );
}

// src/components/vm/RAM.vue
<template>
  <div>
    <label
      for="memory"
      class="form-label"
    >RAM</label>
    <div class="input-group">
      <input
        id="memory"
        v-model="memory"
        type="number"
        class="form-control"
        min="1"
        :max="maxMemory"
      >
      <span class="input-group-text">GiB</span>
    </div>
  </div>
</template>

<script>
export default {
    name: 'RAM',
    computed: {
        maxMemory() {
            return this.$store.state.system.memory;
        },
        memory: {
            get() {
                return this.$store.state.vm.config.memory;
            },
            set(value) {
                this.$store.commit('vm/config/patch', {
                    memory: value,
                });
            },
        },
    },
};
</script>
