// src/components/SpiceServer.tsx
import * as React from 'react';

import { HorizontalLayout } from './HorizontalLayout';
import {
    setSpiceServerEnabled as setEnabled,
    setSpiceServerPassword as setPassword,
    setSpiceServerPort as setPort,
    setSpiceServerTicketing as setTicketing,
    setSpiceServerUsbRedirection as setUsbRedirection,
} from '../store/slices/vm';
import { useAppDispatch, useAppSelector } from '../store/hooks';

function SpiceServerEnabled() {
    const { enabled } = useAppSelector(state => state.vm.spiceServer);
    const dispatch = useAppDispatch();

    return (
        <div className="form-check mb-2">
            <input
                id="spiceServerEnabled"
                className="form-check-input"
                type="checkbox"
                checked={enabled}
                onChange={event => dispatch(setEnabled(event.target.checked))}
            />
            <label className="form-check-label" htmlFor="spiceServerEnabled">
                Enable SPICE server
            </label>
        </div>
    );
}

function SpiceServerTicketing() {
    const { ticketing } = useAppSelector(state => state.vm.spiceServer);
    const dispatch = useAppDispatch();

    return (
        <div className="form-check mb-2">
            <input
                id="spiceServerTicketing"
                className="form-check-input"
                type="checkbox"
                checked={ticketing}
                onChange={event => dispatch(setTicketing(event.target.checked))}
            />
            <label className="form-check-label" htmlFor="spiceServerTicketing">
                With ticketing
            </label>
        </div>
    );
}

function SpiceServerUsbRedirection() {
    const checked = useAppSelector(state => state.vm.spiceServer.usbRedirection);
    const dispatch = useAppDispatch();

    return (
        <div className="form-check mb-2">
            <input
                id="spiceServerUsbRedirection"
                className="form-check-input"
                type="checkbox"
                checked={checked}
                onChange={event => dispatch(setUsbRedirection(event.target.checked))}
            />
            <label className="form-check-label" htmlFor="spiceServerUsbRedirection">
                With USB redirection
            </label>
        </div>
    );
}

function SpiceServerPort() {
    const { port } = useAppSelector(state => state.vm.spiceServer);
    const dispatch = useAppDispatch();

    return (
        <div>
            <label htmlFor="spiceServerPort" className="form-label">
                SPICE server port
            </label>
            <input
                id="spiceServerPort"
                className="form-control"
                type="number"
                min="0"
                max="65535"
                value={port}
                onChange={event => dispatch(setPort(Number.parseInt(event.target.value)))}
            />
        </div>
    );
}

function SpiceServerPassword() {
    const { password, ticketing } = useAppSelector(state => state.vm.spiceServer);
    const dispatch = useAppDispatch();

    return (
        <div>
            <label htmlFor="spiceServerPassword" className="form-label">
                SPICE server password
            </label>
            <input
                id="spiceServerPassword"
                className="form-control"
                type="text"
                value={password}
                onChange={event => dispatch(setPassword(event.target.value))}
                disabled={!ticketing}
            />
        </div>
    );
}

export function SpiceServer() {
    const { enabled } = useAppSelector(state => state.vm.spiceServer);

    return (
        <div>
            <HorizontalLayout even={true}>
                <div>
                    <SpiceServerEnabled />
                </div>
                <div>
                    {enabled && <SpiceServerTicketing />}
                    {enabled && <SpiceServerUsbRedirection />}
                </div>
            </HorizontalLayout>
            {enabled && (
                <HorizontalLayout even={true}>
                    <SpiceServerPort />
                    <SpiceServerPassword />
                </HorizontalLayout>
            )}
        </div>
    );
}

// src/components/vm/SpiceServer.vue
<template>
  <div>
    <HorizontalLayout :even="true">
      <div>
        <div class="form-check mb-2">
          <input
            id="spiceServerEnabled"
            v-model="spiceServerEnabled"
            class="form-check-input"
            type="checkbox"
          >
          <label
            class="form-check-label"
            for="spiceServerEnabled"
          >
            Enable SPICE server
          </label>
        </div>
      </div>
      <div>
        <div
          v-if="spiceServerEnabled"
          class="form-check mb-2"
        >
          <input
            id="spiceServerTicketing"
            v-model="spiceServerTicketing"
            class="form-check-input"
            type="checkbox"
          >
          <label
            class="form-check-label"
            for="spiceServerTicketing"
          >
            With ticketing
          </label>
        </div>
        <div
          v-if="spiceServerEnabled"
          class="form-check mb-2"
        >
          <input
            id="spiceServerUsbRedirection"
            v-model="spiceServerUsbRedirection"
            class="form-check-input"
            type="checkbox"
          >
          <label
            class="form-check-label"
            for="spiceServerUsbRedirection"
          >
            With USB redirection
          </label>
        </div>
      </div>
    </HorizontalLayout>
    <HorizontalLayout
      v-if="spiceServerEnabled"
      :even="true"
    >
      <div>
        <label
          for="spiceServerPort"
          class="form-label"
        >SPICE server port</label>
        <input
          id="spiceServerPort"
          v-model="spiceServerPort"
          class="form-control"
          type="number"
          min="0"
          max="65535"
        >
      </div>
      <div>
        <label
          for="spiceServerPassword"
          class="form-label"
        >SPICE server password</label>
        <input
          id="spiceServerPassword"
          v-model="spiceServerPassword"
          class="form-control"
          type="text"
          :disabled="!spiceServerTicketing"
        >
      </div>
    </HorizontalLayout>
  </div>
</template>

<script>
import HorizontalLayout from '../HorizontalLayout.vue';

export default {
    name: 'SpiceServer',
    components: {
        HorizontalLayout,
    },
    computed: {
        spiceServer() {
            return this.$store.state.vm.config.spiceServer;
        },
        spiceServerEnabled: {
            get() {
                return this.$store.state.vm.config.spiceServer.enabled;
            },
            set(value) {
                this.$store.commit('vm/config/spiceServer/setEnabled', value);
            },
        },
        spiceServerPort: {
            get() {
                return this.$store.state.vm.config.spiceServer.port;
            },
            set(value) {
                this.$store.commit('vm/config/spiceServer/setPort', value);
            },
        },
        spiceServerPassword: {
            get() {
                return this.$store.state.vm.config.spiceServer.password;
            },
            set(value) {
                this.$store.commit('vm/config/spiceServer/setPassword', value);
            },
        },
        spiceServerTicketing: {
            get() {
                return this.$store.state.vm.config.spiceServer.ticketing;
            },
            set(value) {
                this.$store.commit('vm/config/spiceServer/setTicketing', value);
            },
        },
        spiceServerUsbRedirection: {
            get() {
                return this.$store.state.vm.config.spiceServer.usbRedirection;
            },
            set(value) {
                this.$store.commit('vm/config/spiceServer/setUsbRedirection', value);
            },
        },
    },
};
</script>
