// src/components/App/index.tsx
import * as React from 'react';
import { useEffect } from 'react';

import { useAppDispatch } from '../../store/hooks';
import { getInfo } from '../../store/slices/system';
import { loadVmConfig, sendConfigToMainProcess } from '../../store/slices/vm';
import { VmConfig } from '../VmConfig';
import { VmLauncher } from '../VmLauncher';

import './index.css';

export function App() {
    const dispatch = useAppDispatch();

    useEffect(() => {
        dispatch(getInfo());

        electron.vmConfig.onRequestConfig(async (event) => {
            dispatch(sendConfigToMainProcess(event));
        });

        electron.vmConfig.onLoadConfig(async (_event, config) => {
            dispatch(loadVmConfig(config));
        });
    }, []);

    return (
        <div className="app">
            <div className="app-vm-config-wrapper">
                <VmConfig />
            </div>
            <div className="app-launcher-wrapper">
                <VmLauncher />
            </div>
        </div>
    );
}

// src/components/App.vue
<template>
  <div class="app">
    <div class="app-vm-config-wrapper">
      <VmConfig />
    </div>
    <div class="app-launcher-wrapper">
      <VmLauncher />
    </div>
  </div>
</template>

<script>
import VmConfig from './VmConfig.vue';
import VmLauncher from './VmLauncher.vue';

export default {
    components: {
        VmConfig,
        VmLauncher,
    },
    created() {
        electron.vmConfig.onRequestConfig(async (event) => { // eslint-disable-line
            const config = this.$store.getters['vm/config/plainObject'];
            
            event.sender.send('vm:request-config-value', JSON.stringify(config));
        });

        electron.vmConfig.onLoadConfig(async (_event, config) => { // eslint-disable-line
            config = JSON.parse(config);

            this.$store.dispatch('vm/config/load', config);
        });

        this.$store.dispatch('system/loadInfo');
    },
};
</script>

<style>
.app {
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
  flex-grow: 1;
  justify-content: center;
  align-items: stretch;
  gap: 1rem;
  margin: 1rem;
}

.app-launcher-wrapper,
.app-vm-config-wrapper {
  flex-grow: 1;
  padding: 0;
  width: 100%;
}
</style>
