// src/components/vm/GraphicsCard.vue
<template>
  <div>
    <label
      for="graphicsCard"
      class="form-label"
    >Graphics card</label>
    <select
      id="graphicsCard"
      v-model="graphicsCard"
      class="form-select"
    >
      <option
        v-for="option in graphicsCardOptions"
        :key="option.value"
        :value="option.value"
      >
        {{ option.text }}
      </option>
    </select>
  </div>
</template>

<script>
import { GRAPHICS_CARDS } from '@/enums';

export default {
    name: 'GraphicsCard',
    data() {
        return {
            graphicsCardOptions: GRAPHICS_CARDS,
        };
    },
    computed: {
        graphicsCard: {
            get() {
                return this.$store.state.vm.config.graphics.card;
            },
            set(value) {
                this.$store.commit('vm/config/patch', {
                    graphics: {
                        card: value,
                    },
                });
            },
        },
    },
};
</script>

<style>

</style>

// src/components/GraphicsCard.tsx
import * as React from 'react';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { setGraphicsCard } from '../store/slices/vm';
import { GraphicsCard as GraphicsCardEnum } from '../enums';

const GraphicsCardList: Array<{ text: string; value: GraphicsCardEnum }> = [
    {
        text: 'None',
        value: GraphicsCardEnum.NONE,
    },
    {
        text: 'Cirrus',
        value: GraphicsCardEnum.CIRRUS,
    },
    {
        text: 'Standard',
        value: GraphicsCardEnum.STANDARD,
    },
    {
        text: 'VMware SVGA-II',
        value: GraphicsCardEnum.VMWARE,
    },
    {
        text: 'QXL',
        value: GraphicsCardEnum.QXL,
    },
    {
        text: 'VirtIO',
        value: GraphicsCardEnum.VIRTIO,
    },
];

export function GraphicsCard() {
    const { card } = useAppSelector(state => state.vm.graphics);
    const dispatch = useAppDispatch();

    return (
        <div>
            <label htmlFor="graphicsCard" className="form-label">
                Graphics card
            </label>
            <select
                id="graphicsCard"
                className="form-select"
                value={card}
                onChange={event => dispatch(setGraphicsCard(event.target.value as GraphicsCardEnum))}
            >
                {GraphicsCardList.map(({ text, value }) => (
                    <option key={value} value={value}>
                        {text}
                    </option>
                ))}
            </select>
        </div>
    );
}
