// src/components/vm/NetworkSettings.vue
<template>
  <div class="form-check">
    <input
      id="networkingEnabled"
      v-model="networkingEnabled"
      class="form-check-input"
      type="checkbox"
    >
    <label
      class="form-check-label"
      for="networkingEnabled"
    >
      Enable networking
    </label>
  </div>
</template>

<script>
export default {
    name: 'NetworkSettings',
    computed: {
        networkingEnabled: {
            get() {
                return this.$store.state.vm.config.networking.enabled;
            },
            set(value) {
                this.$store.commit('vm/patchConfig', {
                    networking: {
                        enabled: value,
                    },
                });
            },
        },
    },
};
</script>

// src/components/NetworkSettings.tsx
import * as React from 'react';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { setNetworkEnabled } from '../store/slices/vm';

export function NetworkSettings() {
    const {enabled} = useAppSelector(state => state.vm.network);
    const dispatch = useAppDispatch();

    return (
        <div>
            <div className="form-check">
                <input
                    id="networkingEnabled"
                    className="form-check-input"
                    type="checkbox"
                    checked={enabled}
                    onChange={event => dispatch(setNetworkEnabled(event.target.checked))}
                />
                <label className="form-check-label" htmlFor="networkingEnabled">
                    Enable networking
                </label>
            </div>
        </div>
    );
}
