// src/components/vm/OpticalDrive.vue
<template>
  <div>
    <label
      for="cdromPath"
      class="form-label"
    >Optical drive
    </label>
    <div class="input-group mb-2">
      <input
        id="cdromPath"
        class="form-control"
        type="text"
        :value="cdromPath"
        :disabled="!cdromEnabled"
        readonly
      >
      <button
        class="btn btn-outline-primary"
        type="button"
        :disabled="!cdromEnabled"
        @click="requestCdromPath"
      >
        Select
      </button>
    </div>
    <div>
      <div class="form-check">
        <input
          id="cdromEnabled"
          v-model="cdromEnabled"
          class="form-check-input"
          type="checkbox"
        >
        <label
          class="form-check-label"
          for="cdromEnabled"
        >
          Enabled
        </label>
      </div>
    </div>
  </div>
</template>

<script>
export default {
    name: 'OpticalDrive',
    computed: {
        cdromEnabled: {
            get() {
                return this.$store.state.vm.config.cdrom.enabled;
            },
            set(value) {
                this.$store.commit('vm/config/cdrom/setEnabled', value);
            }
        },
        cdromPath() {
            return this.$store.state.vm.config.cdrom.path;
        }
    },
    methods: {
        async requestCdromPath() {
            // eslint-disable-next-line no-undef
            const path = await electron.vmConfig.requestCdromPath();
            
            this.$store.commit('vm/config/cdrom/setPath', path.replaceAll('\\', '\\\\'));
        },
    }
};
</script>

// src/components/OpticalDrive.tsx
import * as React from 'react';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { setOpticalDriveEnabled, setOpticalDrivePath } from '../store/slices/vm';

export function OpticalDrive() {
    const { enabled, path } = useAppSelector(state => state.vm.cdrom);
    const dispatch = useAppDispatch();

    return (
        <div>
            <label htmlFor="cdromPath" className="form-label">
                Optical drive
            </label>
            <div className="input-group mb-2">
                <input id="cdromPath" className="form-control" type="text" value={path} disabled={!enabled} readOnly />
                <button
                    className="btn btn-outline-primary"
                    type="button"
                    onClick={() => dispatch(setOpticalDrivePath())}
                    disabled={!enabled}
                >
                    Select
                </button>
            </div>
            <div>
                <div className="form-check">
                    <input
                        id="cdromEnabled"
                        className="form-check-input"
                        type="checkbox"
                        checked={enabled}
                        onChange={event => dispatch(setOpticalDriveEnabled(event.target.checked))}
                    />
                    <label className="form-check-label" htmlFor="cdromEnabled">
                        Enabled
                    </label>
                </div>
            </div>
        </div>
    );
}
