// src/components/vm/SpiceAgent.vue
<template>
  <div>
    <div class="form-check">
      <input
        id="spiceAgentEnabled"
        v-model="spiceAgentEnabled"
        class="form-check-input"
        type="checkbox"
      >
      <label
        class="form-check-label"
        for="spiceAgentEnabled"
      >
        Enable SPICE agent
      </label>
    </div>
    <div />
  </div>
</template>

<script>
export default {
    name: 'SpiceAgent',
    computed: {
        spiceAgentEnabled: {
            get() {
                return this.$store.state.vm.config.spiceAgent.enabled;
            },
            set(value) {
                this.$store.commit('vm/config/patch', {
                    spiceAgent: {
                        enabled: value,
                    },
                });
            },
        },
    },
};
</script>

// src/components/SpiceAgent.tsx
import * as React from 'react';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { setSpiceAgentEnabled } from '../store/slices/vm';

export function SpiceAgent() {
    const enabled = useAppSelector(state => state.vm.spiceAgent.enabled);
    const dispatch = useAppDispatch();

    return (
        <div>
            <div className="form-check">
                <input
                    id="spiceAgentEnabled"
                    className="form-check-input"
                    type="checkbox"
                    checked={enabled}
                    onChange={event => dispatch(setSpiceAgentEnabled(event.target.checked))}
                />
                <label className="form-check-label" htmlFor="spiceAgentEnabled">
                    Enable SPICE agent
                </label>
            </div>
            <div />
        </div>
    );
}
